# Practicle 2

In [1]:
import numpy as np

x = np.array([[10, 30, 50, 70, 90], [20, 60, 100, 140, 180]])

print("Original array:")
print(x)

Original array:
[[ 10  30  50  70  90]
 [ 20  60 100 140 180]]


## a

In [2]:
print("Mean")
print(np.mean(x, axis=1))

Mean
[ 50. 100.]


In [3]:
print("standard deviation")
print(np.std(x, axis=1))

standard deviation
[28.28427125 56.56854249]


In [4]:
print("variance ")
print(np.var(x, axis=1))

variance 
[ 800. 3200.]


## b

In [5]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
print('array -', B)

indices = np.argsort(B)
print('sorted indices - ',indices)

array - [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
sorted indices -  [8 2 6 9 3 7 1 0 4 5]


## c

In [6]:
import numpy as np

print('Enter Array size ')
m = int(input("m = "))
n = int(input("n = "))

new_array = np.random.randint(50, size=(m,n))

print("Random set of rows from 2D array array:")
print(new_array)

Enter Array size 
m = 5
n = 6
Random set of rows from 2D array array:
[[ 5  1 23  5 17 21]
 [14 39 29 40  2 29]
 [12  1 24 27 19 31]
 [13 45 11 45 28 18]
 [10 12  7 29 20 19]]


In [7]:
print('Shape')
print(new_array.shape)

Shape
(5, 6)


In [8]:
print('Type')
print(type(new_array))

Type
<class 'numpy.ndarray'>


In [9]:
print('Dtype')
print(new_array.dtype)

Dtype
int32


In [10]:
# Reshape
print('Reshape array')

m = int(input("m = "))
n = int(input("n = "))

np.reshape(new_array, (m,n))

Reshape array
m = 6
n = 5


array([[ 5,  1, 23,  5, 17],
       [21, 14, 39, 29, 40],
       [ 2, 29, 12,  1, 24],
       [27, 19, 31, 13, 45],
       [11, 45, 28, 18, 10],
       [12,  7, 29, 20, 19]])

In [11]:
print('Test non zero value')
print(np.any(new_array))

Test non zero value
True


In [12]:
print('Test nan value')
np.isnan(new_array)

Test nan value


array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])