In [1]:
# 2(a)

import numpy as np
data = np.random.randint(10,size =(7,5))
data

array([[8, 5, 7, 0, 6],
       [0, 0, 0, 7, 0],
       [5, 8, 2, 9, 4],
       [0, 6, 5, 2, 3],
       [5, 7, 3, 6, 0],
       [1, 4, 7, 8, 2],
       [3, 7, 1, 8, 4]])

In [2]:
for i in range(7):
    m = np.mean(data[i])
    s = np.std(data[i])
    v = np.var(data[i])
    print("Mean of row ",i+1,": ",m)
    print("Standard Deviation of row ",i+1,": ",s)
    print("Variance of row ",i+1,": ",v)
    print("\n")

Mean of row  1 :  5.2
Standard Deviation of row  1 :  2.7856776554368237
Variance of row  1 :  7.76


Mean of row  2 :  1.4
Standard Deviation of row  2 :  2.8
Variance of row  2 :  7.839999999999999


Mean of row  3 :  5.6
Standard Deviation of row  3 :  2.5768197453450252
Variance of row  3 :  6.640000000000001


Mean of row  4 :  3.2
Standard Deviation of row  4 :  2.1354156504062622
Variance of row  4 :  4.5600000000000005


Mean of row  5 :  4.2
Standard Deviation of row  5 :  2.481934729198171
Variance of row  5 :  6.159999999999999


Mean of row  6 :  4.4
Standard Deviation of row  6 :  2.727636339397171
Variance of row  6 :  7.44


Mean of row  7 :  4.6
Standard Deviation of row  7 :  2.5768197453450252
Variance of row  7 :  6.640000000000001




In [3]:
# 2(b)

B = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
print("Original array:")
print(B)
i = np.argsort(B)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[56 48 22 41 78 91 24 46  8 33]
Indices of the sorted elements of a given array:
[8 2 6 9 3 7 1 0 4 5]


In [4]:
# 2(c)

m = int(input("No.of rows of 2D array: "))
n = int(input("No.of columns of 2D array: "))
arr = np.random.randint(100,size =(m,n))
arr

No.of rows of 2D array: 3
No.of columns of 2D array: 4


array([[10, 65, 63, 19],
       [62, 69, 72, 22],
       [77, 60, 15, 73]])

In [5]:
print("Shape of the array: ", np.shape(arr))

Shape of the array:  (3, 4)


In [6]:
print("Type of the array: ", type(arr))

Type of the array:  <class 'numpy.ndarray'>


In [7]:
print("Shape of the array: ", arr.dtype)

Shape of the array:  int64


In [8]:
arr1 = arr.reshape(n,m)
arr1

array([[10, 65, 63],
       [19, 62, 69],
       [72, 22, 77],
       [60, 15, 73]])

In [9]:
# 2(d)

arr2 = np.array([5,2,0,6,np.nan,9,28,0,6,0,np.nan,7,3,0])
arr2

array([ 5.,  2.,  0.,  6., nan,  9., 28.,  0.,  6.,  0., nan,  7.,  3.,
        0.])

In [10]:
z = np.where(arr2==0)
z

(array([ 2,  7,  9, 13]),)

In [11]:
nz = np.nonzero(arr2)
nz

(array([ 0,  1,  3,  4,  5,  6,  8, 10, 11, 12]),)

In [12]:
na = (np.argwhere(np.isnan(arr2)))
na

array([[ 4],
       [10]])